<?php

// Squiz.WhiteSpace.FunctionOpeningBraceSpace
function spaceAfterOpen()
{

    $var = 1;
}

function spaceBeforeClose()
{
    $var = 1;

}


// Squiz.WhiteSpace.FunctionSpacing
function fn1()
{
}
function fn2()
{
}




function fn3()
{
}



$var = 1;
function fn4()
{
}

/** docs */



function phpdoc1()
{
}

/** docs */
function phpdoc2()
{
}
/** docs */
function phpdoc3()
{
}
/** docs */


function phpdoc4()
{
}


/** docs */


function phpdoc5()
{
}

#[attribute]


function attribute1()
{
}

#[attribute]
function attribute2()
{
}
#[attribute]
function attribute3()
{
}
#[attribute]


function attribute4()
{
}

/** docs */
#[attribute]


function attributeDoc1()
{
}

/** docs */
#[attribute]
function attributeDoc2()
{
}
/** docs */
#[attribute]
function attributeDoc3()
{
}
/** docs */
#[attribute]


function attributeDoc4()
{
}

#[attribute]
/** docs */


function docAttribute1()
{
}

#[attribute]
/** docs */
function docAttribute2()
{
}
#[attribute]
/** docs */
function docAttribute3()
{
}
#[attribute]
/** docs */


function docAttribute4()
{
}
