name: Build
on:
    push:
        branches:
            - "main"
    pull_request:

jobs:
    lint:
        strategy:
            matrix:
                php: [7.2]

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Install dependencies
              run: composer install --no-progress

            - name: Check coding style
              run: vendor/bin/phpcs

            - name: Run static analyser
              run: vendor/bin/phpstan analyse

    test:
        strategy:
            fail-fast: false
            matrix:
                php: [7.2, 7.3, 7.4, 8.0, 8.1, 8.2]
                mode: [low, high]

        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup PHP, with composer and extensions
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Install dependencies
              run: |
                  [[ "${{ matrix.mode }}" = "low" ]] && composer update --no-progress --prefer-lowest || true
                  [[ "${{ matrix.mode }}" = "high" ]] && composer update --no-progress || true
                  [[ "${{ matrix.mode }}" = "low" ]] && composer bin tools update --no-progress || true

            - name: Run testing
              run: vendor/bin/phpunit
